In [1]:
import numpy as np

In [2]:
# Creating NumPy arrays: ndarrays <---> python lists
# 1D array. 10x1 matrix

a1 = np.arange(10)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
a2 = np.arange(0, 10, 2)

In [6]:
print(a2)

[0 2 4 6 8]


In [7]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [8]:
# Creating 2D arrays
# Using zeros, shape 2x3 matrix

a4 = np.zeros((2,3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Specific number instead of 0s with .full function
# 2x3 array with all 8s
a5 = np.full((2,3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [10]:
# 4x4 identity matrix with .eye function:

a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# rank 2 array (2 rows 4 cols) w/ random values in 0.0, 1.0

a7 = np.random.random((2,4))
print(a7)

[[0.28444234 0.44988974 0.49946172 0.32490626]
 [0.24750676 0.25694645 0.72467489 0.01915515]]


In [12]:
# Create numpy array from a python list: (rank 1 array)

list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


In [13]:
# Array Indexing

print(r1[0])
print(r1[1])

1
2


In [14]:
# 2d array from python list:

list2 = [6,7,8,9,10]
r2 = np.array([list1, list2])
print(r2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
# format: r2[row, column]

print(r2.shape)
print(r2[0,0])
print(r2[0,1])
print(r2[1,0])

(2, 5)
1
2
6


In [16]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1[[2,4]])

[3 5]


In [17]:
# Boolean Indexing

print(r1>2)

[False False  True  True  True]


In [18]:
print(r1[r1>2])

[3 4 5]


In [19]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
odd_num = nums[nums%2==1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
# Slicing Arrays

a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [9,8,7,6,5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [22]:
# a[row 1 to 3 (not inclusive), first 3 columns]
# df[start:stop (rows), start:stop (columns)]

b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [23]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]


In [24]:
# the slice is a reference, not a copy of the original array. Consider:

b3 = a[1:,2:]
print(b3)

[[6 7 8]
 [7 6 5]]


In [25]:
b3[0,2]=88
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [26]:
# slicing is dependent on how you slice it: Rank 2 array vs rank 1 array
b4 = a[2:,:]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In [27]:
b5 = a[2, :]
print(b5)
print(b5.shape)

[9 8 7 6 5]
(5,)


In [28]:
# Reshaping arrays. Reshape function:
# convert(rank 2 array w 1 row, -1=correct # of cols) <---> reshape(1,5)
b5 = b5.reshape(1,-1)
print(b5)

[[9 8 7 6 5]]


In [29]:
# no cols input, let function decide number of rows. to convert rank 2 to rank 1, can use flatten() or ravel() functions.
b4.reshape(-1,)

array([9, 8, 7, 6, 5])

In [30]:
x1 = np.array([[1,2,3], [4,5,6]])
y1 = np.array([[7,8,9], [2,3,4]])
print(x1)
print(y1)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [2 3 4]]


In [31]:
print(x1+y1)

[[ 8 10 12]
 [ 6  8 10]]


In [32]:
# adds numbers in same position together and returns array of the same dimension
x = np.array([2,3])
y = np.array([4,2])
z = x+y
print(z)

[6 5]


In [33]:
# add function:
np.add(x1,y1)

array([[ 8, 10, 12],
       [ 6,  8, 10]])

In [34]:
# subtract, multiply, divide functions or -, *, /

### BMI exercise

(weight kg/ height m)/height m <br>
underweight if BMI < 18.5 <br>
overweight if BMI > 25 <br>
normal weight if 18.5 <= BMI <= 25

In [35]:
names = np.array(['Ann', 'Joe', 'Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [36]:
BMI = (weights/heights)/heights

In [37]:
print(names, BMI)

['Ann' 'Joe' 'Mark'] [28.88888889 14.51836889 23.046875  ]


In [38]:
print("Overweight:", names[BMI>25])
print("Normal:", names[(BMI>=18.5)&(BMI<=25)])
print("Underweight:", names[BMI<18.5])

Overweight: ['Ann']
Normal: ['Mark']
Underweight: ['Joe']


In [39]:
# Dot Product. Multiplication, then sum of the products

x = np.array([2,3])
y = np.array([4,2])
np.dot(x,y)

14

In [40]:
# 2x3 array and 3x2 matrix multiplication --> 2x2 array
x2 = np.array([[1,2,3], [4,5,6]])
y2 = np.array([[7,8],[9,10],[11,12]])
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


In [48]:
x2 = np.matrix([[1,2], [4,5]])
y2 = np.matrix([[7,8], [2,3]])

In [49]:
x2

matrix([[1, 2],
        [4, 5]])

In [50]:
y2

matrix([[7, 8],
        [2, 3]])

In [58]:
x2 = np.array([[1,2], [4,5]])
y2 = np.array([[7,8], [2,3]])
x2 = np.asmatrix(x2)
y2 = np.asmatrix(y2)

In [ ]:
# When multiplying matrices, the result is the dot product. When multiplying arrays, the result is element by element
# multiplication.

In [61]:
print(x2 * y2)

[[11 14]
 [38 47]]


In [68]:
# Cumulative sum function:
# cumsum function also takes an axis argument. axis=0 specifies the sum of columns while axis=1 specifies rows
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(a.cumsum())
print(a.cumsum(axis=0))
print(a.cumsum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [79]:
# Numpy sorting
# first method does not modify the array while the second one does:
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages)
print(sorted_ages)
ages

[ 5 12 13 34 37]


array([34, 12, 37,  5, 13])

In [76]:
#this method modifies the array:

ages.sort()
ages

array([ 5, 12, 13, 34, 37])

In [81]:
# argsort() function returns the indices of the order in which the array would have been sorted:
# Cell needs to be ran with the original ages array.
print(ages.argsort())

# you can use the sorted indices for the age by using this:
print(ages[ages.argsort()])

[3 1 4 0 2]
[ 5 12 13 34 37]


In [83]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe',])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76, 1.2, 1.68, 0.5, 1.25])
sort_indices = np.argsort(ages)

In [85]:
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])# 

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


In [87]:
# argsort by persons (name) 
sort_indices_name = np.argsort(persons)
print(persons[sort_indices_name])
print(ages[sort_indices_name])
print(heights[sort_indices_name])

['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]


In [89]:
# Using [::-1] to reverse the order of the array?

reverse_sort_indices_name = np.argsort(persons)[::-1]
print(persons[reverse_sort_indices_name])
print(ages[reverse_sort_indices_name])
print(heights[reverse_sort_indices_name])

['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
[ 5 37 12 34 13]
[0.5  1.68 1.2  1.76 1.25]


In [126]:
# Array assignment:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [123]:
list1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [127]:
a2 = a1
print(a1)
print(a2)

#you can set the array to another variable, but it creates a copy by reference. a2 is pointing to a1, so any changes will
#appear on both.

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [128]:
a2[0][0] = 11
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [129]:
# Copying by view (Shallow Copy). means you can change the shape of a1 without affecting a2.

# Rerun the assignment above
a2 = a1.view()
a1[0][0] = 11
print(a1)
print(a2)


[[11  2  3  4]
 [ 5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


In [131]:
a1.shape = 1, -1
print(a1)
print(a2)

[[11  2  3  4  5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


In [137]:
# Copying by value (Deep Copy)

a1 = np.array(list1)
a2 = a1.copy()
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [140]:
a1[0,0] = 11
print(a1)
print(a2)

[[11  2  3  4]
 [ 5  6  7  8]]
[[1 2 3 4]
 [5 6 7 8]]
