In [1]:
import numpy as np

In [2]:
# Creating NumPy arrays: ndarrays <---> python lists
# 1D array. 10x1 matrix

a1 = np.arange(10)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
a2 = np.arange(0, 10, 2)

In [8]:
print(a2)

[0 2 4 6 8]


In [9]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [11]:
# Creating 2D arrays
# Using zeros, shape 2x3 matrix

a4 = np.zeros((2,3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Specific number instead of 0s with .full function
# 2x3 array with all 8s
a5 = np.full((2,3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [13]:
# 4x4 identity matrix with .eye function:

a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# rank 2 array (2 rows 4 cols) w/ random values in 0.0, 1.0

a7 = np.random.random((2,4))
print(a7)

[[0.01695538 0.13779671 0.26026199 0.69630257]
 [0.43481178 0.81491115 0.97834406 0.99121072]]


In [15]:
# Create numpy array from a python list: (rank 1 array)

list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


In [17]:
# Array Indexing

print(r1[0])
print(r1[1])

1
2


In [18]:
# 2d array from python list:

list2 = [6,7,8,9,10]
r2 = np.array([list1, list2])
print(r2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
# format: r2[row, column]

print(r2.shape)
print(r2[0,0])
print(r2[0,1])
print(r2[1,0])

(2, 5)
1
2
6


In [21]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1[[2,4]])

[3 5]


In [22]:
# Boolean Indexing

print(r1>2)

[False False  True  True  True]


In [23]:
print(r1[r1>2])

[3 4 5]


In [24]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
odd_num = nums[nums%2==1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


In [27]:
# Slicing Arrays

a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [9,8,7,6,5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [28]:
# a[row 1 to 3 (not inclusive), first 3 columns]
# df[start:stop (rows), start:stop (columns)]

b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [29]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]
